plugins {
    id 'java-library'
}

group = 'dolbunov.andrey.qa'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0",
            "com.codeborne:selenide:7.16.2")
}
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
test {
    useJUnitPlatform()
}